### ISSUE TITLE
The price of terminus premium is varying across different documents

### ISSUE THREAD

**Issue by chengs** [Crystalnix/Termius-Documentation#7]
Hello, I note that the price of Termius Preminum is not the same in your documents.

1. On the website, it is 2.49 USD per month.
2. On the [support website](http://support.termius.com/knowledgebase/articles/1158928-what-is-termius-premium), it is 9.99 USD per year.
3. On the [github document](https://github.com/Crystalnix/Termius-Documentation/blob/21815875d51bad6df5f266ecbb86466b1391e425/general/subscriptions.md#features), it is 6 USD per year.

Besides, I say frankly, the current price for a year is too expensive. Can you provide a lower price regarding each single client?

**Comment by rkudiyarov** [comment]
Thanks for pointing out the inconsistency we had in our documentation. 

What do you use Termius for? What Premium Feature are required for your usage?

**Comment by chengs** [comment]
Basically, to write code on a remote server.
Though i don't activate the premium option, the agent forwarding function will be very helpful in my case.

**Comment by rkudiyarov** [comment]
Thanks for your answer.

Would you pay $15 USD for the following set of Premium features: 
* Background sessions
* Terminal tabs
* Agent forwarding
* Touch ID

This set of features would be available only on one device.

**Comment by Deihmos** [comment]
I agree. As a single user I cannot justify paying this much. I like the snippits and would like to use sftp but for that's too much for those features. Why isn't there a one time fee? I am not interested in sync.

**Comment by leitenky** [comment]
I love the app but 84$ is way too much.  If a reasonable 1 time fee was available I would purchase this app in an instant

**Comment by neilalexander** [comment]
Admittedly I love using Termius for MOSH but I am also very put off the pricing model.

If there was a one-off purchase fee (up to 20 USD) that would allow SFTP, background sessions and terminal tabs on iOS only then I would pay that *in a heartbeat*.

I just can't justify the current pricing, nor the fact that it's subscription-based, when I'm not particularly interested in synchronisation features or more advanced things like chaining or agent forwarding.

**Comment by tripptuttle** [comment]
So, I really love the app. Nothing comes close on iOS for quick issues on the go. But, I haven’t been able to find any info about an education/academic discount. I’ve found for most tech companies that’s SOP. Am I missing something about academic pricing?
